services:
  - type: web
    name: street-vendor-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: street-vendor-db
          property: connectionString

databases:
  - name: street-vendor-db
    databaseName: street_vendor
    user: street_vendor_user 