# Generated by Django 5.2 on 2025-05-05 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationverification',
            name='verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorlocation',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorlocation',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='locationverification',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='locations.vendorlocation'),
        ),
        migrations.AlterUniqueTogether(
            name='locationverification',
            unique_together={('location', 'verified_by')},
        ),
    ]
